# Generated by Django 4.1.5 on 2023-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_comprehension_user_confidence_user_curiosity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
